export const MATCH_TYPES = {
  START_MATCH: 'START_MATCH',
  UPDATE_SCORE: 'UPDATE_SCORE',
  UPDATE_OVER: 'UPDATE_OVER',
  ADD_EXTRA: 'ADD_EXTRA',
  UPDATE_TIMER: 'UPDATE_TIMER',
  TOGGLE_TIMER: 'TOGGLE_TIMER',
  SAVE_MATCH: 'SAVE_MATCH',
  LOAD_MATCHES: 'LOAD_MATCHES',
  SET_DARK_MODE: 'SET_DARK_MODE',
};
